# Generated by Django 4.2.11 on 2024-03-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("weather_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="year",
            options={"ordering": ["-year"], "verbose_name_plural": "Years"},
        ),
        migrations.CreateModel(
            name="Seasonaldata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("win", models.CharField(max_length=25)),
                ("spr", models.CharField(max_length=25)),
                ("sum", models.CharField(max_length=25)),
                ("aut", models.CharField(max_length=25)),
                (
                    "params",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.parameter",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.region",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.year",
                    ),
                ),
            ],
        ),
    ]
