# Generated by Django 4.2.11 on 2024-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_app", "0003_alter_seasonaldata_aut_alter_seasonaldata_spr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonaldata",
            name="win",
            field=models.FloatField(blank=True, max_length=25, null=True),
        ),
    ]
