# Generated by Django 4.2.11 on 2024-03-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("weather_app", "0005_alter_seasonaldata_aut_alter_seasonaldata_spr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="column",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="SeasonalData2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "params",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.parameter",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.region",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.season",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_app.year",
                    ),
                ),
            ],
        ),
    ]
