# Generated by Django 5.0.2 on 2024-03-30 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0006_season_column_seasonaldata2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonaldata2',
            name='season',
        ),
        migrations.RemoveField(
            model_name='seasonaldata',
            name='params',
        ),
        migrations.RemoveField(
            model_name='seasonaldata',
            name='region',
        ),
        migrations.RemoveField(
            model_name='seasonaldata',
            name='year',
        ),
        migrations.RemoveField(
            model_name='seasonaldata2',
            name='params',
        ),
        migrations.RemoveField(
            model_name='seasonaldata2',
            name='region',
        ),
        migrations.RemoveField(
            model_name='seasonaldata2',
            name='year',
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_monthly_data', to='weather_app.month')),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params_monthly_data', to='weather_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_monthly_data', to='weather_app.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_monthly_data', to='weather_app.year')),
            ],
            options={
                'verbose_name_plural': 'Monthly Data',
            },
        ),
        migrations.DeleteModel(
            name='MasterTable',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Seasonaldata',
        ),
        migrations.DeleteModel(
            name='SeasonalData2',
        ),
    ]
