# Generated by Django 5.0.2 on 2024-03-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0007_remove_seasonaldata2_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Annual',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('column', models.IntegerField(default=1)),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params_annual', to='weather_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_annual', to='weather_app.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_annual', to='weather_app.year')),
            ],
            options={
                'verbose_name_plural': '9. Annual Data ',
            },
        ),
        migrations.CreateModel(
            name='MonthlyData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.month')),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params_season', to='weather_app.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_season', to='weather_app.region')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_season', to='weather_app.season')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_season', to='weather_app.year')),
            ],
            options={
                'verbose_name_plural': '7. Seasons Data',
            },
        ),
    ]
