# Generated by Django 5.0.2 on 2024-03-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0008_annual_season_annualdata_monthlydata1_seasonaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.DeleteModel(
            name='Annual',
        ),
        migrations.AlterModelOptions(
            name='annualdata',
            options={'verbose_name_plural': 'Annual Data'},
        ),
        migrations.AlterModelOptions(
            name='seasonaldata',
            options={'verbose_name_plural': 'Seasonal Data'},
        ),
        migrations.RemoveField(
            model_name='annualdata',
            name='column',
        ),
        migrations.AlterField(
            model_name='annualdata',
            name='params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.parameter'),
        ),
        migrations.AlterField(
            model_name='annualdata',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.region'),
        ),
        migrations.AlterField(
            model_name='annualdata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.year'),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.month'),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.parameter'),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.region'),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.year'),
        ),
        migrations.AlterField(
            model_name='seasonaldata',
            name='params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.parameter'),
        ),
        migrations.AlterField(
            model_name='seasonaldata',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.region'),
        ),
        migrations.AlterField(
            model_name='seasonaldata',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.season'),
        ),
        migrations.AlterField(
            model_name='seasonaldata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.year'),
        ),
        migrations.AddField(
            model_name='annualdata',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather_app.finaltotal'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MonthlyData1',
        ),
    ]
