# Generated by Django 5.0.2 on 2024-03-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0009_finaltotal_delete_annual_alter_annualdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finaltotal',
            options={'verbose_name_plural': 'FinalTotal'},
        ),
    ]
