# Generated by Django 5.0.2 on 2024-04-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0014_alter_year_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualdata',
            options={'verbose_name_plural': '3. Annual Data'},
        ),
        migrations.AlterModelOptions(
            name='finaltotal',
            options={'verbose_name_plural': '7. FinalTotal'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['id'], 'verbose_name_plural': '8. Months'},
        ),
        migrations.AlterModelOptions(
            name='monthlydata',
            options={'verbose_name_plural': '1. Monthly Data'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['id'], 'verbose_name_plural': '6. Parameters'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': '5. Regions'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name_plural': '8. Seasons'},
        ),
        migrations.AlterModelOptions(
            name='seasonaldata',
            options={'verbose_name_plural': '2. Seasonal Data'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year'], 'verbose_name_plural': '4. Years'},
        ),
    ]
